import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "SimranBeedi",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",  // Favicon icon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* Favicon links */}
        <link rel="icon" href="/public/favicon.ico" type="image/x-icon">
<link rel="icon" href="/public/favicon-16x16.png" sizes="16x16">
<link rel="icon" href="/public/favicon-32x32.png" sizes="32x32">

        <meta name="theme-color" content="#ffffff" />
      </head>
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 
        overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
